Update build-images to allow running sl as well as building it
My laptop has weird company-customised versions of various tools which makes it a pain to build vanilla OSS projects, so I'd like to do development work inside a container. Using the CI build-images seems smarter than trying to come up with my own DIY dev-images, the only downside being that there are a couple of missing runtime-dependencies. Eg, when running ./sl, I get an error that the locale is invalid:

```
root@e11f03ad868a:/workspaces/sapling/eden/scm# ./sl
Traceback (most recent call last):
  File "/workspaces/sapling/eden/scm/sapling/__init__.py", line 64, in run
    from . import dispatch
  File "/workspaces/sapling/eden/scm/sapling/dispatch.py", line 27, in <module>
    from . import (
  File "/workspaces/sapling/eden/scm/sapling/cmdutil.py", line 29, in <module>
    from . import (
  File "/workspaces/sapling/eden/scm/sapling/crecord.py", line 32, in <module>
    locale.setlocale(locale.LC_ALL, "")
  File "/usr/lib/python3.10/locale.py", line 620, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
```